# bash
# Autogenerated from man page /usr/local/share/man/man1/bash.1
complete -c bash -o 'd\'\'' --description 'null argument removal.'
complete -c bash -s R --description 'True if the shell variable varname is set and is a name reference.'

