# cjpeg
# Autogenerated from man page /usr/local/share/man/man1/cjpeg.1
complete -c cjpeg -o rgb1 --description 'Create RGB JPEG file with reversible color transform.'
complete -c cjpeg -o bgycc --description 'Create big gamut YCC JPEG file.'

