# cs2cs
# Autogenerated from man page /usr/local/share/man/man1/cs2cs.1
complete -c cs2cs -o 't<a>' --description 'Where a specifies a character employed as the first character to denote a con…'
complete -c cs2cs -s d --description 'UNINDENT . sp New in version 5. 2.'
complete -c cs2cs -o 'l<' --description 'List projection identifiers that can be selected with +proj.'
complete -c cs2cs -o 'w<n>' --description 'Where n is the number of significant fractional digits to employ for seconds …'
complete -c cs2cs -o 'W<n>' --description 'Where n is the number of significant fractional digits to employ for seconds …'

