# djpeg
# Autogenerated from man page /usr/local/share/man/man1/djpeg.1
complete -c djpeg -o rgb --description 'Force RGB output even if JPEG file is grayscale.'
complete -c djpeg -o gif0 --description 'Select GIF output format (uncompressed).'

