# geod
# Autogenerated from man page /usr/local/share/man/man1/geod.1
complete -c geod -o 't<a>' --description 'Where a specifies a character employed as the first character to denote a con…'
complete -c geod -s F --description 'Where format is a printf format string to control the output form of the dist…'
complete -c geod -o 'w<n>' --description 'Where n is the number of significant fractional digits to employ for seconds …'
complete -c geod -o 'W<n>' --description 'Where n is the number of significant fractional digits to employ for seconds …'
complete -c geod -o '66d31\'50.141' --description 'where the first two values are the azimuth from Boston to Portland, the back …'

