# git-format-patch
# Autogenerated from man page /usr/local/share/man/man1/git-format-patch.1
complete -c git-format-patch -l cover-from-description --description 'Controls which parts of the cover letter will be automatically populated usin…'
complete -c git-format-patch -l no-base --description 'option overrides a format. useAutoBase configuration.'

