# git-clone
# Autogenerated from man page /usr/local/share/man/man1/git-clone.1
complete -c git-clone -l sparse --description 'Initialize the sparse-checkout file so the working directory starts with only…'

