# git-config
# Autogenerated from man page /usr/local/share/man/man1/git-config.1
complete -c git-config -l show-scope --description 'Similar to --show-origin in that it augments the output of all queried config…'
complete -c git-config -l cover-from-description --description 'option in git-format-patch(1).  format. signature.'

