# git-fetch
# Autogenerated from man page /usr/local/share/man/man1/git-fetch.1
complete -c git-fetch -l write-commit-graph --description 'Write a commit-graph after fetching.  This overrides the config setting fetch.'

