# git-fast-import
# Autogenerated from man page /usr/local/share/man/man1/git-fast-import.1
complete -c git-fast-import -l allow-unsafe-features --description 'Many command-line options can be provided as part of the fast-import stream i…'

