# git-rebase
# Autogenerated from man page /usr/local/share/man/man1/git-rebase.1
complete -c git-rebase -l empty --description 'How to handle commits that are not empty to start and are not clean cherry-pi…'
complete -c git-rebase -l apply --description '.'

