# jpegtran
# Autogenerated from man page /usr/local/share/man/man1/jpegtran.1
complete -c jpegtran -o wipe --description 'Wipe (gray out) a rectangular subarea of width W, height H starting at point …'
complete -c jpegtran -o drop --description 'Drop another image .'

