# mosh-server
# Autogenerated from man page /usr/local/share/man/man1/mosh-server.1
complete -c mosh-server -s s --description 'bind to the local interface used for an incoming SSH connection, given in the…'
complete -c mosh-server -s v --description 'Print some debugging information even after detaching.'
complete -c mosh-server -s i --description 'IP address of the local interface to bind (for multihomed hosts).'
complete -c mosh-server -s p --description 'UDP port number or port-range to bind.'
complete -c mosh-server -s c --description 'Number of colors to advertise to applications through TERM (e. g.  8, 256).'
complete -c mosh-server -s l --description 'Locale-related environment variable to try as part of a fallback environment,…'

