# pg_controldata
# Autogenerated from man page /Applications/Postgres.app/Contents/Versions/latest/share/man/man1/pg_controldata.1
complete -c pg_controldata -s V --description 'and.'
complete -c pg_controldata -l version --description 'pg_controldata version and exit.  It also supports options.'
complete -c pg_controldata -s '?' --description 'and.'
complete -c pg_controldata -l help --description 'ENVIRONMENT.'

