# rpl
# Autogenerated from man page /usr/local/share/man/man1/rpl.1
complete -c rpl -s i --description 'Ignore case of old_str .'
complete -c rpl -s w --description 'Whole words (old_str bounded by white space in file) .'
complete -c rpl -s q --description 'Quiet mode (no output at all) . RS Good for shell scripts, etc. RE.'
complete -c rpl -s v --description 'Verbose mode (lots of output) .'
complete -c rpl -s R --description 'Search directories recursively .'
complete -c rpl -s x --description 'Specify file suffixes to search.  (e. g.  ". html", ". c", etc.'
complete -c rpl -s p --description 'Prompt for each file . RS  rpl will prompt you before scanning each file.'
complete -c rpl -s s --description 'Simulation mode .'
complete -c rpl -s e --description 'Honor Escapes .'
complete -c rpl -s f --description 'Force mode .'
complete -c rpl -s d --description 'Don\'t change modification times .'
complete -c rpl -s t --description 'Use $TMPDIR for temporary files .'
complete -c rpl -s L --description 'Display the software license .'
complete -c rpl -s h --description 'Display a brief summary of options.'

