# tiffcrop
# Autogenerated from man page /usr/local/share/man/man1/tiffcrop.1
complete -c tiffcrop -s 1 --description 'it will results in infinite number of the rows per strip.'
complete -c tiffcrop -s D --description 'Display program progress and/or dump raw data to non-TIFF files.'

