# tldr
# Autogenerated from man page /usr/local/share/man/man1/tldr.1
complete -c tldr -s v --description 'verbose output.'
complete -c tldr -l version --description 'output version information and exit.'
complete -c tldr -s h -l help --description 'display help and exit.'
complete -c tldr -s u -l update --description 'update local database and exit.'
complete -c tldr -s c -l clear-cache --description 'remove local database and exit.'
complete -c tldr -s p -l platform --description 'select platform, supported are linux / osx / sunos / common.'
complete -c tldr -s r -l render --description 'render a local page for testing purposes EXIT STATUS 0 on success, any other …'

