# tred
# Autogenerated from man page /usr/local/share/man/man1/tred.1
complete -c tred -s v --description 'Verbose output.'
complete -c tred -s '?' --description 'Print usage information.  OPERANDS The following operand is supported:.'

