# unbound
# Autogenerated from man page /usr/local/share/man/man8/unbound.8
complete -c unbound -s p --description 'Don\'t use a pidfile.'
complete -c unbound -s V --description 'Show the version number and build options, and exit.  SEE ALSO unbound.'

