;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        hydra-cljr-toplevel-form-menu/cljr-extract-function
        indent-for-tab-command
        ))

(setq mc/cmds-to-run-once
      '(
        hydra-cljr-code-menu/cljr-promote-function
        hydra-cljr-code-menu/nil
        mac-mwheel-scroll
        scroll-bar-toolkit-scroll
        ))
